server:
  port: 8088
eureka:
  client:
    service-url:
      defaultZone: http://lujingkeji:ljkj1005!@192.168.200.12:8761/eureka/
    register-with-eureka: false
spring:
  redis:
    host: 192.168.200.17
    database: 3
    password: cdtnb...
harbor:
  backup-dir: /Users/july/temp/harbor