server:
  servlet:
    context-path: /harbor
  shutdown: graceful
spring:
  application:
    name: harbor
  jackson:
    serialization:
      write-dates-as-timestamps: true
  lifecycle:
    timeout-per-shutdown-phase: 15s
eureka:
  instance:
    prefer-ip-address: true