harbor:
  auto-register-apps-cron: '-'
server:
  servlet:
    context-path: /harbor
  shutdown: graceful
spring:
  application:
    name: harbor
  jackson:
    serialization:
      write-dates-as-timestamps: true
      fail-on-empty-beans: false
      fail-on-unwrapped-type-identifiers: false
  lifecycle:
    timeout-per-shutdown-phase: 15s
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  boot:
    admin:
      context-path: /spring-admin
      basic-auth:
        username: ENC(OUqOvEe2svcQSFabr6BJz8yqGKinaawLzMmW1rtMBktyYtSq94HL5Ce2lY4v/z+2)
        password: ENC(6AGEXqNhA3R7lt4/wlBipZYCAhcQ9Y0/jszJEhs4gaFYG9YXLWlOAfwCOzkf24Q9)
eureka:
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers,metrics,prometheus
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    loggers:
      enabled: true
    metrics:
      enabled: true