server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://lujingkeji:ljkj1005!@192.168.200.12:8761/eureka/
spring:
  redis:
    host: 192.168.200.17
    database: 5
    password: cdtnb...