server:
  servlet:
    context-path: /harbor
  shutdown: graceful
spring:
  application:
    name: harbor
  jackson:
    serialization:
      write-dates-as-timestamps: true
  lifecycle:
    timeout-per-shutdown-phase: 15s
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
eureka:
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: health,httptrace,info,loggers,metrics
  endpoint:
    health:
      enabled: true
    httptrace:
      enabled: true
    info:
      enabled: true
    loggers:
      enabled: true
    metrics:
      enabled: true