harbor:
  auto-register-apps-cron: '-'
server:
  servlet:
    context-path: /harbor
  shutdown: graceful
spring:
  application:
    name: harbor
  jackson:
    serialization:
      write-dates-as-timestamps: true
      fail-on-empty-beans: false
      fail-on-unwrapped-type-identifiers: false
  lifecycle:
    timeout-per-shutdown-phase: 15s
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  boot:
    admin:
      context-path: /spring-admin
      monitor:
        status-lifetime: 15000ms
        status-interval: 10000ms
        default-retries: 3
      basic-auth:
        username: ENC(OUqOvEe2svcQSFabr6BJz8yqGKinaawLzMmW1rtMBktyYtSq94HL5Ce2lY4v/z+2)
        password: ENC(6AGEXqNhA3R7lt4/wlBipZYCAhcQ9Y0/jszJEhs4gaFYG9YXLWlOAfwCOzkf24Q9)
eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      management-context-path: ${server.servlet.context-path}/actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers,metrics,prometheus
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    loggers:
      enabled: true
    metrics:
      enabled: true